version: "3.8"
services:
    mongodb:
        container_name: mongodb_scraping
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - mongo_data:/data/db
        restart: always
volumes:
    mongo_data:
